// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockstorageinterfaces

import (
	"go-project/internal/domain/task/models"
	models0 "go-project/internal/domain/user/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositories creates a new instance of MockRepositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositories {
	mock := &MockRepositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositories is an autogenerated mock type for the Repositories type
type MockRepositories struct {
	mock.Mock
}

type MockRepositories_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositories) EXPECT() *MockRepositories_Expecter {
	return &MockRepositories_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRepositories
func (_mock *MockRepositories) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositories_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRepositories_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRepositories_Expecter) Close() *MockRepositories_Close_Call {
	return &MockRepositories_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRepositories_Close_Call) Run(run func()) *MockRepositories_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositories_Close_Call) Return(err error) *MockRepositories_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositories_Close_Call) RunAndReturn(run func() error) *MockRepositories_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function for the type MockRepositories
func (_mock *MockRepositories) CreateTask(uid string, task models.Task) (uuid.UUID, error) {
	ret := _mock.Called(uid, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, models.Task) (uuid.UUID, error)); ok {
		return returnFunc(uid, task)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.Task) uuid.UUID); ok {
		r0 = returnFunc(uid, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.Task) error); ok {
		r1 = returnFunc(uid, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockRepositories_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - uid string
//   - task models.Task
func (_e *MockRepositories_Expecter) CreateTask(uid interface{}, task interface{}) *MockRepositories_CreateTask_Call {
	return &MockRepositories_CreateTask_Call{Call: _e.mock.On("CreateTask", uid, task)}
}

func (_c *MockRepositories_CreateTask_Call) Run(run func(uid string, task models.Task)) *MockRepositories_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.Task
		if args[1] != nil {
			arg1 = args[1].(models.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositories_CreateTask_Call) Return(uUID uuid.UUID, err error) *MockRepositories_CreateTask_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepositories_CreateTask_Call) RunAndReturn(run func(uid string, task models.Task) (uuid.UUID, error)) *MockRepositories_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockRepositories
func (_mock *MockRepositories) CreateUser(user models0.User) (uuid.UUID, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models0.User) (uuid.UUID, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(models0.User) uuid.UUID); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models0.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepositories_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user models0.User
func (_e *MockRepositories_Expecter) CreateUser(user interface{}) *MockRepositories_CreateUser_Call {
	return &MockRepositories_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *MockRepositories_CreateUser_Call) Run(run func(user models0.User)) *MockRepositories_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models0.User
		if args[0] != nil {
			arg0 = args[0].(models0.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositories_CreateUser_Call) Return(uUID uuid.UUID, err error) *MockRepositories_CreateUser_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepositories_CreateUser_Call) RunAndReturn(run func(user models0.User) (uuid.UUID, error)) *MockRepositories_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskByTID provides a mock function for the type MockRepositories
func (_mock *MockRepositories) DeleteTaskByTID(uid string, tid string) error {
	ret := _mock.Called(uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskByTID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(uid, tid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositories_DeleteTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskByTID'
type MockRepositories_DeleteTaskByTID_Call struct {
	*mock.Call
}

// DeleteTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
func (_e *MockRepositories_Expecter) DeleteTaskByTID(uid interface{}, tid interface{}) *MockRepositories_DeleteTaskByTID_Call {
	return &MockRepositories_DeleteTaskByTID_Call{Call: _e.mock.On("DeleteTaskByTID", uid, tid)}
}

func (_c *MockRepositories_DeleteTaskByTID_Call) Run(run func(uid string, tid string)) *MockRepositories_DeleteTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositories_DeleteTaskByTID_Call) Return(err error) *MockRepositories_DeleteTaskByTID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositories_DeleteTaskByTID_Call) RunAndReturn(run func(uid string, tid string) error) *MockRepositories_DeleteTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByUID provides a mock function for the type MockRepositories
func (_mock *MockRepositories) DeleteUserByUID(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByUID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositories_DeleteUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByUID'
type MockRepositories_DeleteUserByUID_Call struct {
	*mock.Call
}

// DeleteUserByUID is a helper method to define mock.On call
//   - id string
func (_e *MockRepositories_Expecter) DeleteUserByUID(id interface{}) *MockRepositories_DeleteUserByUID_Call {
	return &MockRepositories_DeleteUserByUID_Call{Call: _e.mock.On("DeleteUserByUID", id)}
}

func (_c *MockRepositories_DeleteUserByUID_Call) Run(run func(id string)) *MockRepositories_DeleteUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositories_DeleteUserByUID_Call) Return(err error) *MockRepositories_DeleteUserByUID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositories_DeleteUserByUID_Call) RunAndReturn(run func(id string) error) *MockRepositories_DeleteUserByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByTID provides a mock function for the type MockRepositories
func (_mock *MockRepositories) GetTaskByTID(uid string, tid string) (models.Task, error) {
	ret := _mock.Called(uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByTID")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (models.Task, error)); ok {
		return returnFunc(uid, tid)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) models.Task); ok {
		r0 = returnFunc(uid, tid)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(uid, tid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_GetTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByTID'
type MockRepositories_GetTaskByTID_Call struct {
	*mock.Call
}

// GetTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
func (_e *MockRepositories_Expecter) GetTaskByTID(uid interface{}, tid interface{}) *MockRepositories_GetTaskByTID_Call {
	return &MockRepositories_GetTaskByTID_Call{Call: _e.mock.On("GetTaskByTID", uid, tid)}
}

func (_c *MockRepositories_GetTaskByTID_Call) Run(run func(uid string, tid string)) *MockRepositories_GetTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositories_GetTaskByTID_Call) Return(task models.Task, err error) *MockRepositories_GetTaskByTID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockRepositories_GetTaskByTID_Call) RunAndReturn(run func(uid string, tid string) (models.Task, error)) *MockRepositories_GetTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockRepositories
func (_mock *MockRepositories) GetTasks(uid string) ([]models.Task, error) {
	ret := _mock.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.Task, error)); ok {
		return returnFunc(uid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.Task); ok {
		r0 = returnFunc(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockRepositories_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - uid string
func (_e *MockRepositories_Expecter) GetTasks(uid interface{}) *MockRepositories_GetTasks_Call {
	return &MockRepositories_GetTasks_Call{Call: _e.mock.On("GetTasks", uid)}
}

func (_c *MockRepositories_GetTasks_Call) Run(run func(uid string)) *MockRepositories_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositories_GetTasks_Call) Return(tasks []models.Task, err error) *MockRepositories_GetTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockRepositories_GetTasks_Call) RunAndReturn(run func(uid string) ([]models.Task, error)) *MockRepositories_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockRepositories
func (_mock *MockRepositories) GetUserByEmail(email string) (models0.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 models0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models0.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models0.User); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(models0.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepositories_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockRepositories_Expecter) GetUserByEmail(email interface{}) *MockRepositories_GetUserByEmail_Call {
	return &MockRepositories_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", email)}
}

func (_c *MockRepositories_GetUserByEmail_Call) Run(run func(email string)) *MockRepositories_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositories_GetUserByEmail_Call) Return(user models0.User, err error) *MockRepositories_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepositories_GetUserByEmail_Call) RunAndReturn(run func(email string) (models0.User, error)) *MockRepositories_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUID provides a mock function for the type MockRepositories
func (_mock *MockRepositories) GetUserByUID(id string) (models0.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUID")
	}

	var r0 models0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models0.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models0.User); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(models0.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_GetUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUID'
type MockRepositories_GetUserByUID_Call struct {
	*mock.Call
}

// GetUserByUID is a helper method to define mock.On call
//   - id string
func (_e *MockRepositories_Expecter) GetUserByUID(id interface{}) *MockRepositories_GetUserByUID_Call {
	return &MockRepositories_GetUserByUID_Call{Call: _e.mock.On("GetUserByUID", id)}
}

func (_c *MockRepositories_GetUserByUID_Call) Run(run func(id string)) *MockRepositories_GetUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositories_GetUserByUID_Call) Return(user models0.User, err error) *MockRepositories_GetUserByUID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepositories_GetUserByUID_Call) RunAndReturn(run func(id string) (models0.User, error)) *MockRepositories_GetUserByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockRepositories
func (_mock *MockRepositories) GetUsers() ([]models0.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []models0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models0.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models0.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models0.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockRepositories_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
func (_e *MockRepositories_Expecter) GetUsers() *MockRepositories_GetUsers_Call {
	return &MockRepositories_GetUsers_Call{Call: _e.mock.On("GetUsers")}
}

func (_c *MockRepositories_GetUsers_Call) Run(run func()) *MockRepositories_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositories_GetUsers_Call) Return(users []models0.User, err error) *MockRepositories_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepositories_GetUsers_Call) RunAndReturn(run func() ([]models0.User, error)) *MockRepositories_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskByTID provides a mock function for the type MockRepositories
func (_mock *MockRepositories) UpdateTaskByTID(uid string, tid string, req models.TaskRequest) (models.Task, error) {
	ret := _mock.Called(uid, tid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskByTID")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, models.TaskRequest) (models.Task, error)); ok {
		return returnFunc(uid, tid, req)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, models.TaskRequest) models.Task); ok {
		r0 = returnFunc(uid, tid, req)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, models.TaskRequest) error); ok {
		r1 = returnFunc(uid, tid, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositories_UpdateTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskByTID'
type MockRepositories_UpdateTaskByTID_Call struct {
	*mock.Call
}

// UpdateTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
//   - req models.TaskRequest
func (_e *MockRepositories_Expecter) UpdateTaskByTID(uid interface{}, tid interface{}, req interface{}) *MockRepositories_UpdateTaskByTID_Call {
	return &MockRepositories_UpdateTaskByTID_Call{Call: _e.mock.On("UpdateTaskByTID", uid, tid, req)}
}

func (_c *MockRepositories_UpdateTaskByTID_Call) Run(run func(uid string, tid string, req models.TaskRequest)) *MockRepositories_UpdateTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.TaskRequest
		if args[2] != nil {
			arg2 = args[2].(models.TaskRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositories_UpdateTaskByTID_Call) Return(task models.Task, err error) *MockRepositories_UpdateTaskByTID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockRepositories_UpdateTaskByTID_Call) RunAndReturn(run func(uid string, tid string, req models.TaskRequest) (models.Task, error)) *MockRepositories_UpdateTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByUID provides a mock function for the type MockRepositories
func (_mock *MockRepositories) UpdateUserByUID(id string, userReq models0.UserUpdateRequest) (string, string, error) {
	ret := _mock.Called(id, userReq)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByUID")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, models0.UserUpdateRequest) (string, string, error)); ok {
		return returnFunc(id, userReq)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models0.UserUpdateRequest) string); ok {
		r0 = returnFunc(id, userReq)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, models0.UserUpdateRequest) string); ok {
		r1 = returnFunc(id, userReq)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, models0.UserUpdateRequest) error); ok {
		r2 = returnFunc(id, userReq)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositories_UpdateUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByUID'
type MockRepositories_UpdateUserByUID_Call struct {
	*mock.Call
}

// UpdateUserByUID is a helper method to define mock.On call
//   - id string
//   - userReq models0.UserUpdateRequest
func (_e *MockRepositories_Expecter) UpdateUserByUID(id interface{}, userReq interface{}) *MockRepositories_UpdateUserByUID_Call {
	return &MockRepositories_UpdateUserByUID_Call{Call: _e.mock.On("UpdateUserByUID", id, userReq)}
}

func (_c *MockRepositories_UpdateUserByUID_Call) Run(run func(id string, userReq models0.UserUpdateRequest)) *MockRepositories_UpdateUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models0.UserUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(models0.UserUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositories_UpdateUserByUID_Call) Return(s string, s1 string, err error) *MockRepositories_UpdateUserByUID_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockRepositories_UpdateUserByUID_Call) RunAndReturn(run func(id string, userReq models0.UserUpdateRequest) (string, string, error)) *MockRepositories_UpdateUserByUID_Call {
	_c.Call.Return(run)
	return _c
}
