// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktaskservice

import (
	"go-project/internal/domain/task/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateTask(uid string, task models.Task) (uuid.UUID, error) {
	ret := _mock.Called(uid, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, models.Task) (uuid.UUID, error)); ok {
		return returnFunc(uid, task)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.Task) uuid.UUID); ok {
		r0 = returnFunc(uid, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.Task) error); ok {
		r1 = returnFunc(uid, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - uid string
//   - task models.Task
func (_e *MockRepository_Expecter) CreateTask(uid interface{}, task interface{}) *MockRepository_CreateTask_Call {
	return &MockRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", uid, task)}
}

func (_c *MockRepository_CreateTask_Call) Run(run func(uid string, task models.Task)) *MockRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.Task
		if args[1] != nil {
			arg1 = args[1].(models.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateTask_Call) Return(uUID uuid.UUID, err error) *MockRepository_CreateTask_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepository_CreateTask_Call) RunAndReturn(run func(uid string, task models.Task) (uuid.UUID, error)) *MockRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskByTID provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteTaskByTID(uid string, tid string) error {
	ret := _mock.Called(uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskByTID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(uid, tid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskByTID'
type MockRepository_DeleteTaskByTID_Call struct {
	*mock.Call
}

// DeleteTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
func (_e *MockRepository_Expecter) DeleteTaskByTID(uid interface{}, tid interface{}) *MockRepository_DeleteTaskByTID_Call {
	return &MockRepository_DeleteTaskByTID_Call{Call: _e.mock.On("DeleteTaskByTID", uid, tid)}
}

func (_c *MockRepository_DeleteTaskByTID_Call) Run(run func(uid string, tid string)) *MockRepository_DeleteTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteTaskByTID_Call) Return(err error) *MockRepository_DeleteTaskByTID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteTaskByTID_Call) RunAndReturn(run func(uid string, tid string) error) *MockRepository_DeleteTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByTID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTaskByTID(uid string, tid string) (models.Task, error) {
	ret := _mock.Called(uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByTID")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (models.Task, error)); ok {
		return returnFunc(uid, tid)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) models.Task); ok {
		r0 = returnFunc(uid, tid)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(uid, tid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByTID'
type MockRepository_GetTaskByTID_Call struct {
	*mock.Call
}

// GetTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
func (_e *MockRepository_Expecter) GetTaskByTID(uid interface{}, tid interface{}) *MockRepository_GetTaskByTID_Call {
	return &MockRepository_GetTaskByTID_Call{Call: _e.mock.On("GetTaskByTID", uid, tid)}
}

func (_c *MockRepository_GetTaskByTID_Call) Run(run func(uid string, tid string)) *MockRepository_GetTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetTaskByTID_Call) Return(task models.Task, err error) *MockRepository_GetTaskByTID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockRepository_GetTaskByTID_Call) RunAndReturn(run func(uid string, tid string) (models.Task, error)) *MockRepository_GetTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTasks(uid string) ([]models.Task, error) {
	ret := _mock.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.Task, error)); ok {
		return returnFunc(uid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.Task); ok {
		r0 = returnFunc(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockRepository_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - uid string
func (_e *MockRepository_Expecter) GetTasks(uid interface{}) *MockRepository_GetTasks_Call {
	return &MockRepository_GetTasks_Call{Call: _e.mock.On("GetTasks", uid)}
}

func (_c *MockRepository_GetTasks_Call) Run(run func(uid string)) *MockRepository_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetTasks_Call) Return(tasks []models.Task, err error) *MockRepository_GetTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockRepository_GetTasks_Call) RunAndReturn(run func(uid string) ([]models.Task, error)) *MockRepository_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskByTID provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateTaskByTID(uid string, tid string, req models.TaskRequest) (models.Task, error) {
	ret := _mock.Called(uid, tid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskByTID")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, models.TaskRequest) (models.Task, error)); ok {
		return returnFunc(uid, tid, req)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, models.TaskRequest) models.Task); ok {
		r0 = returnFunc(uid, tid, req)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, models.TaskRequest) error); ok {
		r1 = returnFunc(uid, tid, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskByTID'
type MockRepository_UpdateTaskByTID_Call struct {
	*mock.Call
}

// UpdateTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
//   - req models.TaskRequest
func (_e *MockRepository_Expecter) UpdateTaskByTID(uid interface{}, tid interface{}, req interface{}) *MockRepository_UpdateTaskByTID_Call {
	return &MockRepository_UpdateTaskByTID_Call{Call: _e.mock.On("UpdateTaskByTID", uid, tid, req)}
}

func (_c *MockRepository_UpdateTaskByTID_Call) Run(run func(uid string, tid string, req models.TaskRequest)) *MockRepository_UpdateTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.TaskRequest
		if args[2] != nil {
			arg2 = args[2].(models.TaskRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateTaskByTID_Call) Return(task models.Task, err error) *MockRepository_UpdateTaskByTID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockRepository_UpdateTaskByTID_Call) RunAndReturn(run func(uid string, tid string, req models.TaskRequest) (models.Task, error)) *MockRepository_UpdateTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}
