// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockusers

import (
	"go-project/internal/domain/user/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(user models.User) (string, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.User) (string, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(models.User) string); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(models.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user models.User
func (_e *MockUserService_Expecter) CreateUser(user interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(user models.User)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.User
		if args[0] != nil {
			arg0 = args[0].(models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(s string, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(user models.User) (string, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByUID provides a mock function for the type MockUserService
func (_mock *MockUserService) DeleteUserByUID(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByUID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_DeleteUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByUID'
type MockUserService_DeleteUserByUID_Call struct {
	*mock.Call
}

// DeleteUserByUID is a helper method to define mock.On call
//   - id string
func (_e *MockUserService_Expecter) DeleteUserByUID(id interface{}) *MockUserService_DeleteUserByUID_Call {
	return &MockUserService_DeleteUserByUID_Call{Call: _e.mock.On("DeleteUserByUID", id)}
}

func (_c *MockUserService_DeleteUserByUID_Call) Run(run func(id string)) *MockUserService_DeleteUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_DeleteUserByUID_Call) Return(err error) *MockUserService_DeleteUserByUID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_DeleteUserByUID_Call) RunAndReturn(run func(id string) error) *MockUserService_DeleteUserByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByUID(id string) (models.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUID")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUID'
type MockUserService_GetUserByUID_Call struct {
	*mock.Call
}

// GetUserByUID is a helper method to define mock.On call
//   - id string
func (_e *MockUserService_Expecter) GetUserByUID(id interface{}) *MockUserService_GetUserByUID_Call {
	return &MockUserService_GetUserByUID_Call{Call: _e.mock.On("GetUserByUID", id)}
}

func (_c *MockUserService_GetUserByUID_Call) Run(run func(id string)) *MockUserService_GetUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByUID_Call) Return(user models.User, err error) *MockUserService_GetUserByUID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_GetUserByUID_Call) RunAndReturn(run func(id string) (models.User, error)) *MockUserService_GetUserByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUsers() ([]models.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
func (_e *MockUserService_Expecter) GetUsers() *MockUserService_GetUsers_Call {
	return &MockUserService_GetUsers_Call{Call: _e.mock.On("GetUsers")}
}

func (_c *MockUserService_GetUsers_Call) Run(run func()) *MockUserService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserService_GetUsers_Call) Return(users []models.User, err error) *MockUserService_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_GetUsers_Call) RunAndReturn(run func() ([]models.User, error)) *MockUserService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function for the type MockUserService
func (_mock *MockUserService) LoginUser(userReq models.UserRequest) (models.User, error) {
	ret := _mock.Called(userReq)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.UserRequest) (models.User, error)); ok {
		return returnFunc(userReq)
	}
	if returnFunc, ok := ret.Get(0).(func(models.UserRequest) models.User); ok {
		r0 = returnFunc(userReq)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(models.UserRequest) error); ok {
		r1 = returnFunc(userReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockUserService_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - userReq models.UserRequest
func (_e *MockUserService_Expecter) LoginUser(userReq interface{}) *MockUserService_LoginUser_Call {
	return &MockUserService_LoginUser_Call{Call: _e.mock.On("LoginUser", userReq)}
}

func (_c *MockUserService_LoginUser_Call) Run(run func(userReq models.UserRequest)) *MockUserService_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserRequest
		if args[0] != nil {
			arg0 = args[0].(models.UserRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_LoginUser_Call) Return(user models.User, err error) *MockUserService_LoginUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_LoginUser_Call) RunAndReturn(run func(userReq models.UserRequest) (models.User, error)) *MockUserService_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByUID provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateUserByUID(id string, userReq models.UserUpdateRequest) (string, string, error) {
	ret := _mock.Called(id, userReq)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByUID")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, models.UserUpdateRequest) (string, string, error)); ok {
		return returnFunc(id, userReq)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.UserUpdateRequest) string); ok {
		r0 = returnFunc(id, userReq)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.UserUpdateRequest) string); ok {
		r1 = returnFunc(id, userReq)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, models.UserUpdateRequest) error); ok {
		r2 = returnFunc(id, userReq)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserService_UpdateUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByUID'
type MockUserService_UpdateUserByUID_Call struct {
	*mock.Call
}

// UpdateUserByUID is a helper method to define mock.On call
//   - id string
//   - userReq models.UserUpdateRequest
func (_e *MockUserService_Expecter) UpdateUserByUID(id interface{}, userReq interface{}) *MockUserService_UpdateUserByUID_Call {
	return &MockUserService_UpdateUserByUID_Call{Call: _e.mock.On("UpdateUserByUID", id, userReq)}
}

func (_c *MockUserService_UpdateUserByUID_Call) Run(run func(id string, userReq models.UserUpdateRequest)) *MockUserService_UpdateUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.UserUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(models.UserUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateUserByUID_Call) Return(s string, s1 string, err error) *MockUserService_UpdateUserByUID_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockUserService_UpdateUserByUID_Call) RunAndReturn(run func(id string, userReq models.UserUpdateRequest) (string, string, error)) *MockUserService_UpdateUserByUID_Call {
	_c.Call.Return(run)
	return _c
}
