// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktasks

import (
	"go-project/internal/domain/task/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) CreateTask(uid string, req models.TaskRequest) (string, error) {
	ret := _mock.Called(uid, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, models.TaskRequest) (string, error)); ok {
		return returnFunc(uid, req)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.TaskRequest) string); ok {
		r0 = returnFunc(uid, req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.TaskRequest) error); ok {
		r1 = returnFunc(uid, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - uid string
//   - req models.TaskRequest
func (_e *MockTaskService_Expecter) CreateTask(uid interface{}, req interface{}) *MockTaskService_CreateTask_Call {
	return &MockTaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", uid, req)}
}

func (_c *MockTaskService_CreateTask_Call) Run(run func(uid string, req models.TaskRequest)) *MockTaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.TaskRequest
		if args[1] != nil {
			arg1 = args[1].(models.TaskRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_CreateTask_Call) Return(s string, err error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTaskService_CreateTask_Call) RunAndReturn(run func(uid string, req models.TaskRequest) (string, error)) *MockTaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskByTID provides a mock function for the type MockTaskService
func (_mock *MockTaskService) DeleteTaskByTID(uid string, tid string) error {
	ret := _mock.Called(uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskByTID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(uid, tid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskService_DeleteTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskByTID'
type MockTaskService_DeleteTaskByTID_Call struct {
	*mock.Call
}

// DeleteTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
func (_e *MockTaskService_Expecter) DeleteTaskByTID(uid interface{}, tid interface{}) *MockTaskService_DeleteTaskByTID_Call {
	return &MockTaskService_DeleteTaskByTID_Call{Call: _e.mock.On("DeleteTaskByTID", uid, tid)}
}

func (_c *MockTaskService_DeleteTaskByTID_Call) Run(run func(uid string, tid string)) *MockTaskService_DeleteTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_DeleteTaskByTID_Call) Return(err error) *MockTaskService_DeleteTaskByTID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskService_DeleteTaskByTID_Call) RunAndReturn(run func(uid string, tid string) error) *MockTaskService_DeleteTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByTID provides a mock function for the type MockTaskService
func (_mock *MockTaskService) GetTaskByTID(uid string, tid string) (models.Task, error) {
	ret := _mock.Called(uid, tid)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByTID")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (models.Task, error)); ok {
		return returnFunc(uid, tid)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) models.Task); ok {
		r0 = returnFunc(uid, tid)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(uid, tid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_GetTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByTID'
type MockTaskService_GetTaskByTID_Call struct {
	*mock.Call
}

// GetTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
func (_e *MockTaskService_Expecter) GetTaskByTID(uid interface{}, tid interface{}) *MockTaskService_GetTaskByTID_Call {
	return &MockTaskService_GetTaskByTID_Call{Call: _e.mock.On("GetTaskByTID", uid, tid)}
}

func (_c *MockTaskService_GetTaskByTID_Call) Run(run func(uid string, tid string)) *MockTaskService_GetTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_GetTaskByTID_Call) Return(task models.Task, err error) *MockTaskService_GetTaskByTID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskService_GetTaskByTID_Call) RunAndReturn(run func(uid string, tid string) (models.Task, error)) *MockTaskService_GetTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockTaskService
func (_mock *MockTaskService) GetTasks(uid string) ([]models.Task, error) {
	ret := _mock.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.Task, error)); ok {
		return returnFunc(uid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.Task); ok {
		r0 = returnFunc(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockTaskService_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - uid string
func (_e *MockTaskService_Expecter) GetTasks(uid interface{}) *MockTaskService_GetTasks_Call {
	return &MockTaskService_GetTasks_Call{Call: _e.mock.On("GetTasks", uid)}
}

func (_c *MockTaskService_GetTasks_Call) Run(run func(uid string)) *MockTaskService_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskService_GetTasks_Call) Return(tasks []models.Task, err error) *MockTaskService_GetTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskService_GetTasks_Call) RunAndReturn(run func(uid string) ([]models.Task, error)) *MockTaskService_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskByTID provides a mock function for the type MockTaskService
func (_mock *MockTaskService) UpdateTaskByTID(uid string, tid string, req models.TaskRequest) (models.Task, error) {
	ret := _mock.Called(uid, tid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskByTID")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, models.TaskRequest) (models.Task, error)); ok {
		return returnFunc(uid, tid, req)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, models.TaskRequest) models.Task); ok {
		r0 = returnFunc(uid, tid, req)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, models.TaskRequest) error); ok {
		r1 = returnFunc(uid, tid, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_UpdateTaskByTID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskByTID'
type MockTaskService_UpdateTaskByTID_Call struct {
	*mock.Call
}

// UpdateTaskByTID is a helper method to define mock.On call
//   - uid string
//   - tid string
//   - req models.TaskRequest
func (_e *MockTaskService_Expecter) UpdateTaskByTID(uid interface{}, tid interface{}, req interface{}) *MockTaskService_UpdateTaskByTID_Call {
	return &MockTaskService_UpdateTaskByTID_Call{Call: _e.mock.On("UpdateTaskByTID", uid, tid, req)}
}

func (_c *MockTaskService_UpdateTaskByTID_Call) Run(run func(uid string, tid string, req models.TaskRequest)) *MockTaskService_UpdateTaskByTID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.TaskRequest
		if args[2] != nil {
			arg2 = args[2].(models.TaskRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_UpdateTaskByTID_Call) Return(task models.Task, err error) *MockTaskService_UpdateTaskByTID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskService_UpdateTaskByTID_Call) RunAndReturn(run func(uid string, tid string, req models.TaskRequest) (models.Task, error)) *MockTaskService_UpdateTaskByTID_Call {
	_c.Call.Return(run)
	return _c
}
