// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockuserservice

import (
	"go-project/internal/domain/user/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateUser(user models.User) (uuid.UUID, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.User) (uuid.UUID, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(models.User) uuid.UUID); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user models.User
func (_e *MockRepository_Expecter) CreateUser(user interface{}) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(user models.User)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.User
		if args[0] != nil {
			arg0 = args[0].(models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(uUID uuid.UUID, err error) *MockRepository_CreateUser_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(user models.User) (uuid.UUID, error)) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByUID provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteUserByUID(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByUID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByUID'
type MockRepository_DeleteUserByUID_Call struct {
	*mock.Call
}

// DeleteUserByUID is a helper method to define mock.On call
//   - id string
func (_e *MockRepository_Expecter) DeleteUserByUID(id interface{}) *MockRepository_DeleteUserByUID_Call {
	return &MockRepository_DeleteUserByUID_Call{Call: _e.mock.On("DeleteUserByUID", id)}
}

func (_c *MockRepository_DeleteUserByUID_Call) Run(run func(id string)) *MockRepository_DeleteUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteUserByUID_Call) Return(err error) *MockRepository_DeleteUserByUID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteUserByUID_Call) RunAndReturn(run func(id string) error) *MockRepository_DeleteUserByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByEmail(email string) (models.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) GetUserByEmail(email interface{}) *MockRepository_GetUserByEmail_Call {
	return &MockRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", email)}
}

func (_c *MockRepository_GetUserByEmail_Call) Run(run func(email string)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) Return(user models.User, err error) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) RunAndReturn(run func(email string) (models.User, error)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByUID(id string) (models.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUID")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUID'
type MockRepository_GetUserByUID_Call struct {
	*mock.Call
}

// GetUserByUID is a helper method to define mock.On call
//   - id string
func (_e *MockRepository_Expecter) GetUserByUID(id interface{}) *MockRepository_GetUserByUID_Call {
	return &MockRepository_GetUserByUID_Call{Call: _e.mock.On("GetUserByUID", id)}
}

func (_c *MockRepository_GetUserByUID_Call) Run(run func(id string)) *MockRepository_GetUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByUID_Call) Return(user models.User, err error) *MockRepository_GetUserByUID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUserByUID_Call) RunAndReturn(run func(id string) (models.User, error)) *MockRepository_GetUserByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUsers() ([]models.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetUsers() *MockRepository_GetUsers_Call {
	return &MockRepository_GetUsers_Call{Call: _e.mock.On("GetUsers")}
}

func (_c *MockRepository_GetUsers_Call) Run(run func()) *MockRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetUsers_Call) Return(users []models.User, err error) *MockRepository_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_GetUsers_Call) RunAndReturn(run func() ([]models.User, error)) *MockRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByUID provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateUserByUID(id string, userReq models.UserUpdateRequest) (string, string, error) {
	ret := _mock.Called(id, userReq)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByUID")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, models.UserUpdateRequest) (string, string, error)); ok {
		return returnFunc(id, userReq)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.UserUpdateRequest) string); ok {
		r0 = returnFunc(id, userReq)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.UserUpdateRequest) string); ok {
		r1 = returnFunc(id, userReq)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, models.UserUpdateRequest) error); ok {
		r2 = returnFunc(id, userReq)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_UpdateUserByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByUID'
type MockRepository_UpdateUserByUID_Call struct {
	*mock.Call
}

// UpdateUserByUID is a helper method to define mock.On call
//   - id string
//   - userReq models.UserUpdateRequest
func (_e *MockRepository_Expecter) UpdateUserByUID(id interface{}, userReq interface{}) *MockRepository_UpdateUserByUID_Call {
	return &MockRepository_UpdateUserByUID_Call{Call: _e.mock.On("UpdateUserByUID", id, userReq)}
}

func (_c *MockRepository_UpdateUserByUID_Call) Run(run func(id string, userReq models.UserUpdateRequest)) *MockRepository_UpdateUserByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.UserUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(models.UserUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateUserByUID_Call) Return(s string, s1 string, err error) *MockRepository_UpdateUserByUID_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockRepository_UpdateUserByUID_Call) RunAndReturn(run func(id string, userReq models.UserUpdateRequest) (string, string, error)) *MockRepository_UpdateUserByUID_Call {
	_c.Call.Return(run)
	return _c
}
